---
baseurl: "http://blog.whylimit.net/"
title: "Why limit - Continuous adventures in software development"
footnotereturnlinkcontents: "↩"
permalinks:
  post: /:year/:month/:title/
canonifyurls: true
builddrafts: false

params:
  Subtitle: ""
  AuthorName: "Ljubomir Zivanovic"
  GitHubUser: "ljubomir"
  SidebarRecentLimit: 5
...